version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:80
#  api:
#    container_name: api
#    build:
#      context: .
#      dockerfile: ./apps/api/Dockerfile
#    ports:
#      - 3001:3001
